# MySQL.  Versions 4.1 and 5.0 are recommended.
# 
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: postgresql
  encoding: unicode
  database: test-ruby_development
  pool: 5
  timeout: 5000
  username: fantgeass
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: ruby_test
  pool: 200
  timeout: 5000
  username: fantgeass
  password:

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: test-ruby_production
  pool: 5
  username: fantgeass
  password:
